name: Data Pipeline CI

on: 
  push: 
    branches: [ master ] 
  pull_request: 
    branches: [ master ] 

jobs:
  pipeline-check:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Upgrade pip, setuptools, and wheel
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Install Microsoft Visual C++ Build Tools
        run: choco install visualcpp-build-tools

      - run: pip install -r requirements.txt

      # Set up MySQL-related environment variables from GitHub Secrets (single secret containing all values)
      - name: Set up MySQL environment variables from GitHub Secrets
        run: |
          echo "MYSQL_USER=$(echo '${{ secrets.ENV_VARIABLES }}' | grep -oP '(?<=MYSQL_USER=)[^ ]+')" >> $GITHUB_ENV
          echo "MYSQL_PASSWORD=$(echo '${{ secrets.ENV_VARIABLES }}' | grep -oP '(?<=MYSQL_PASSWORD=)[^ ]+')" >> $GITHUB_ENV
          echo "MYSQL_HOST=$(echo '${{ secrets.ENV_VARIABLES }}' | grep -oP '(?<=MYSQL_HOST=)[^ ]+')" >> $GITHUB_ENV
          echo "MYSQL_PORT=$(echo '${{ secrets.ENV_VARIABLES }}' | grep -oP '(?<=MYSQL_PORT=)[^ ]+')" >> $GITHUB_ENV
          echo "MYSQL_DB=$(echo '${{ secrets.ENV_VARIABLES }}' | grep -oP '(?<=MYSQL_DB=)[^ ]+')" >> $GITHUB_ENV

      - run: python pipeline.py
